# Generated by Django 4.0.2 on 2022-03-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0002_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='album',
        ),
        migrations.AddField(
            model_name='friend',
            name='album',
            field=models.ManyToManyField(to='social_network.user'),
        ),
    ]
