# Generated by Django 4.0.2 on 2022-03-05 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_one'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='many',
            name='alum',
        ),
        migrations.RemoveField(
            model_name='one',
            name='place',
        ),
        migrations.DeleteModel(
            name='friend',
        ),
        migrations.DeleteModel(
            name='many',
        ),
        migrations.DeleteModel(
            name='one',
        ),
    ]
