# Generated by Django 4.0.2 on 2022-03-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0007_remove_many_alum_remove_one_place_delete_friend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='F',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lof', models.ManyToManyField(related_name='list_of_friends', to='social_network.user')),
                ('lou', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='list_of_users', to='social_network.user')),
            ],
        ),
    ]
