# Generated by Django 4.0.2 on 2022-03-05 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_f'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='F',
            new_name='friends',
        ),
    ]
