# Generated by Django 4.0.2 on 2022-03-09 13:17

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_rename_f_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nameslug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
